# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
dist: xenial

env:
  global:
    - secure: "XAhJXuXqnGlZlU2pGcIQKJ2rF44gIReA0arHwapFII/gR1h+2e6hgqnMXwrZaQa/EvNBaXq7nF3XcTBjrbK+ABeKA/0lOh/7ryIotP0i1YVrca69pSK9BY+Kr1y7ncLMqvoyjBziobOeVZmxbK4RflgUTIO7MKzzb5pNb9SnOK8="
    - secure: "UwH3B4k5Nqt2THYYTY7uRxTPaJXZbK1hHrVsyJjZp/H2uFTYtQTxXpNb9aR7wuHuhLjXwKkq3gEXxEqhfy6V8+ZPbee6MUNvoYe/HhaPjsmTzcVihTBbO9e7g0bIQFc9bzwY15Y1ImshLcDAYvaXwXapy4Z/KadLiBheyqMk8Cs="
    # Scaladocs
    - secure: "FPfJbtXmhyMTh/eh9B/f6JZIv6aw+XZMipYlJsdgMEv+XKzL1tdYbKQv8G4C13lhyBZmOlQAbOhl4mRUBmq0FqG3361Y9SS4o5KfDRkZNErBTb8tveoRgKLkdLPwooAOUmRUeygKmhO4ehdQsMXCZmCk33nDq/ZrNallfnCRdm8="
  matrix:
    - RUN_SET=1
    - RUN_SET=2
    - RUN_SET=3
    - RUN_SET=scaladoc

language: scala

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: localhost

services:
  - docker
  - postgresql

before_script:
  - sudo fallocate -l 5G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile
  - .travis/before-script.sh
  - docker run -d --restart=always -p 8081:80 -v $(pwd)/spark/src/test/resources:/usr/share/nginx/html:ro nginx:stable
  - docker run -d --restart=always -p 9091:9000 -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=password minio/minio:RELEASE.2019-05-02T19-07-09Z server /data
  - .travis/unzip-rasters.sh

jdk:
  - openjdk8

scala:
  - "2.11.12"
  - "2.12.10"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/downloads

script:
  - .travis/build-and-test-docker.sh

notifications:
  email:
    recipients:
      - lossyrob@gmail.com
      - echeipesh@gmail.com
  slack:
    secure: "RPNymWgr5RXN2LpDERitGAP7pckR19znqAlrcuKE46O7saqlenX6ii8ToRHOe1ba0udJO0B1n2R2OzTlw14AkuETyRKX4X8OtVlU/dtfTHfVMbX6+oRPd1g1mfLrLavR5o2ml/KoIvi9QLbNcVHfqoeA+xxW5TJTm9zayRC9d1M="

before_deploy:
  - export GEOTRELLIS_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"
  - ./sbt unidoc

deploy:
  - provider: script
    script: .travis/scaladocs.sh
    skip_cleanup: true
    on:
      repo: locationtech/geotrellis
      branch: master
      condition: "$RUN_SET = 'scaladoc'"
      jdk: openjdk8
      scala: "2.11.12"
