# see http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.9.2
script: ./sbt -mem 1512 test && ./sbt -mem 1512 "project demo" compile && ./sbt -mem 1512 "project geotools" compile && ./sbt -mem 1512 "project tasks" compile && ./sbt -mem 1512 "project benchmark" compile && ./sbt -mem 1512 "project dev" compile && ./sbt -mem 1512 "project server" compile 
notifications:
  email:
    recipients:
      - jmarcus@azavea.com
  irc:
      - "irc.freenode.org#geotrellis"
  use_notice: true
