version: 2.1
executors:
  java-executor-gdal:
    docker:
      - image: quay.io/azavea/openjdk-gdal:2.4-jdk8-slim
      - image: minio/minio:RELEASE.2019-05-02T19-07-09Z
        environment:
          _JAVA_OPTIONS: "-Xms1m -Xmx512m"
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: password
        command: server --address :9091 /data
      - image: cassandra:latest
        environment:
          _JAVA_OPTIONS: "-Xms1m -Xmx512m"
          MAX_HEAP_SIZE: 512m
          HEAP_NEWSIZE: 100m
          CASSANDRA_LISTEN_ADDRESS: 127.0.0.1

  java-executor-gdal-empty:
    docker:
      - image: quay.io/azavea/openjdk-gdal:2.4-jdk8-slim

jobs:
  java:
    parameters:
      executor-type:
        type: executor
      scala-version:
        type: string
      test-set:
        type: string
    executor: << parameters.executor-type >>
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Test
          command: |
            export SCALA_VERSION=<< parameters.scala-version >>
            export RUN_SET=<< parameters.test-set >>
            cd raster/data; unzip geotiff-test-files.zip; cd ~-
            .circleci/build-and-test.sh
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.couriser/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  test-publish:
    jobs:
      - java:
          matrix:
            parameters:
              executor-type: [java-executor-gdal]
              scala-version: ["2.11.12", "2.12.10"]
              test-set: ["1", "2"]
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/
      - java:
          matrix:
            parameters:
              executor-type: [java-executor-gdal-empty]
              scala-version: ["2.11.12", "2.12.10"]
              test-set: ["3"]
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/